# add the necessary instructions
# to create a Docker container image
# for your Go API gateway server

FROM alpine:3.7
RUN apk add --no-cache ca-certificates
COPY . /assignments-tristan6/clients/index.html
EXPOSE 443

# Not sure if you need the expose.
